[tool.poetry]
name = "cpunk_mongo"
version = "0.1.2"
description = ""
authors = ["matfonseca <mfonseca@fi.uba.ar>"]

[tool.poetry.dependencies]
python = "^3.7"
pytest = "^7.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
