[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[project]
name = "gidapptools"
authors = [{ name = "brocaprogs" }]
classifiers = ["License :: OSI Approved :: MIT License"]
license = { file = "LICENSE" }
readme = { file = "README.rst", content-type = "text/x-rst" }
dynamic = ['version', 'description']
requires-python = ">=3.9"
dependencies = [
    "attrs~=22.1",
    "frozendict~=2.3",
    "platformdirs~=2.5",
    "psutil~=5.9",
    "pyparsing~=3.0",
    "tzlocal~=4.2",
    "yarl~=1.8",
    "typing-extensions~=4.4",
]

[project.urls]
Source = "https://github.com/Giddius/GidAppTools"

[project.scripts]
gidapptools-info = "gidapptools.cli_info:cli_show_info"


[project.optional-dependencies]

pyside = ["PySide6~=6.4", "jinja2~=3.1"]
orm = ["peewee~=3.15"]
rich = ["rich~=12.6"]
parsing = ["python-dateutil>=2.8.1"]
all = [
    "PySide6~=6.4",
    "peewee~=3.15",
    "cython~=0.29",
    "rich~=12.6",
    "jinja2~=3.1",
    "python-dateutil>=2.8.1",
]
[tool.flit.sdist]
exclude = [
    "misc",
    "temp",
    "docs",
    "tools",
    ".pydeps",
    "tests",
    ".gitattributes",
    ".gitignore",
    ".editorconfig",
    "planning.todo",
    "tasks.py",
]
[tool.setuptools]
packages = ["gidapptools"]

[tool.autopep8]
ignore = ["E402", "E501", "E731"]
max_line_length = 250

[tool.isort]
balanced_wrapping = true
ensure_newline_before_comments = true
group_by_package = true
import_heading_firstparty = "* Local Imports --------------------------------------------------------------------------------------->"
import_heading_gid = "* Gid Imports ----------------------------------------------------------------------------------------->"
import_heading_qt = "* Qt Imports --------------------------------------------------------------------------------------->"
import_heading_stdlib = "* Standard Library Imports ---------------------------------------------------------------------------->"
import_heading_thirdparty = "* Third Party Imports --------------------------------------------------------------------------------->"
known_gid = ["gid*"]
known_qt = ["PyQt5", "PyQt6", "PySide6", "pyqtgraph"]
length_sort = true
line_length = 200
lines_after_imports = 1
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "QT",
    "GID",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
indented_import_headings = false

[tool.autoflake]
# additional_imports=None
expand_star_imports = true
remove_all_unused_imports = true
remove_duplicate_keys = false
remove_unused_variables = false
ignore_init_module_imports = false


[tool.pytest.ini_options]
addopts = "-rA -vv --durations=0 --capture=tee-sys --show-capture=all --color=auto --code-highlight=yes --cov=gidapptools --cov-report html --html-report=./tools/reports/pytest_report --title='PYTEST REPORT'"

[tool.coverage.report]
omit = ["**/__init__.py"]
exclude_lines = ["if __name__ == .__main__.:", "def __rich__", "def __repr__"]

[tool.coverage.html]
directory = "tools/reports/coverage/html"

[tool.mypy]
