[tool.poetry]
name = "wf-camera-utils"
version = "1.0.28"
description = "utilities for wildflower cameras and raspberry pi"
authors = ["Paul J DeCoursey <paul@decoursey.net>"]
license = "MIT"
readme = "README.md"
packages = [{include = "capture"}, {include = "cuwb_stream"}]


[tool.poetry.dependencies]
python = "^3.9"
ffmpeg-python = "0.2.0"
minio = ">=7.1.12"
pyyaml = ">=6.0"
python-json-logger = ">=2.0.4"
influx_line_protocol = ">=0.1.5"


[tool.poetry.group.dev.dependencies]
pylint = "^2.15.5"
black = "^22.10.0"


[tool.poetry.group.capture.dependencies]
picamera = "1.13"
ffmpeg-python = "0.2.0"
minio = ">=7.1.12"
pyyaml = ">=6.0"
python-json-logger = ">=2.0.4"
influx_line_protocol = ">=0.1.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
