[package]
name = "mini-groove"
version = "0.1.2"
edition = "2021"

[lib]
name = "mini_groove"
crate-type = ["cdylib"]

[dependencies]
geo = "0.23.0"
geojson = "0.24.0"
pyo3 = { version = "0.17.3", features = ["extension-module", "abi3-py37"] }
