[project]
name = "nonebot-plugin-novelai"
version = "0.5.3"
description = "基于nonebot2的novelai绘图插件"
authors = [
    {name = "sena-nana", email = "851183156@qq.com"},
]
dependencies = [
    "aiohttp>=3.8.3",
    "nonebot-adapter-onebot>=2.1.3",
    "nonebot2>=2.0.0b4",
    "aiofiles>=22.1.0",
    "pillow>=9.2.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}
[project.urls]
urls="https://github.com/nonebot-plugin-novelai"
[project.optional-dependencies]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.scripts]
pre_build="pdm export -f setuppy -o setup.py"
build="python setup.py sdist"
post_build="twine upload dist/* -u sena-nana -p wjxpypi02818"
[tool.pdm.dev-dependencies]
dev = [
    "setuptools>=65.4.1",
]