[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bytespace"
version = "1.1.0"
description = "A nice and simple API library for connecting to the bytespace API"
readme = "README.md"
authors = [{ name = "Remy"}]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["bytespace", "rect", "tokorv", "redcubedev", "professordj", "borgor"]
dependencies = [
    "requests",
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/hrszpuk/bytespace.py"
