[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "test_proj_1560"
version = "00.01.01"
authors = [
    { name="Tyler Pantuso", email="tylerpantuso@gmail.com" },
]
description = "This package does nothing"
readme = "README.md"
requires-python = ">3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/TylerPantuso/test-proj-1560"
