[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "Zelden"
version = "0.0.4"
authors = [
  { name="Victor Kolis", email="victorkolis@protonmail.com" },
]
dependencies = ['requests']
maintainers = [
    { name="Victor Kolis", email="victorkolis@protonmail.com" },
]
description = "A True Random Generator Package"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Pynosaur/zelden"
"Bug Tracker" = "https://github.com/Pynosaur/zelden/issues"