[tool.poetry]
name = "continual"
version = "v2.0.0a3"
description = "Lifecyle Management for AI"
authors = ["Continual <support@continual.ai>"]
readme = "README.md"
packages = [
    {include = "continual"}
]

[tool.poetry.scripts]
continual = 'continual.python.cli.cli:cli'

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
grpcio = ">=1.27.1"
pandas = ">=1.0.1"
pyyaml = ">=5.4"
requests = ">=2.23.0"
click = "8.0.4"
tabulate = ">=0.8.6"
halo = ">=0.0.30"
grpcio_status = ">=1.31.0"
grpcio-tools = ">=1.43.0,<=1.48.1"
gitpython = ">=3.1.7"
humanize = ">=2.5.0"
typer = "0.4.0"
yamale = ">=4.0.0"
tqdm = ">=4.54.1"
pandas-gbq = ">=0.14.1"
pytz = ">=2020.5"
fsspec = "2022.3"
rich = ">=9.13.0"
cron-descriptor = ">=1.2.24"
google-cloud-storage = ">=1.33.0"
sqlparse = ">=0.4.2"
toml = ">=0.10.2"
poetry = ">=0.12"
protobuf = "3.20.3"
psutil = ">=5.8.0"
simplejson = ">=3.17.6"
sqlalchemy = ">=1.4.27"
snowflake-sqlalchemy = ">=1.3.3"
sqlalchemy-bigquery = ">=1.4.3" 
sqlalchemy-redshift = ">=0.8.9"
jinja2 = ">=3.1.1"
tableschema = ">=1.20.2"
cloudpickle = ">=2.0.0"
databricks_api = ">=0.8.0"
dill = ">=0.3.4"
GitPython = ">=3.1.27"
mlflow = ">=1.23.1"
numpy = ">=1.21.6"
pyhive = ">=0.6.4"
scikit_learn = ">=1.1.2"
shortuuid = ">=1.0.9"
omegaconf = ">=2.2.3"

[tool.poetry.dev-dependencies]
pytest = ">=5.2"

[build-system]
requires = ["poetry>=0.12"]
