[tool.poetry]
name = "emdy"
version = "0.0.9"
description = "Generate open source and Creative Commons licenses from your command line"
authors = ["celsius narhwal <hello@celsiusnarhwal.dev>"]
readme = "README.md"
license = "MIT"
include = ["README.md"]
keywords = ["license", "open source", "creative commons"]
repository = "https://github.com/celsiusnarhwal/emdy"
classifiers = ["Topic :: Software Development :: Code Generators"]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
inquirerpy = "^0.3.4"
inflect = "^6.0.2"
pyperclip = "^1.8.2"

[tool.poetry.group.dev.dependencies]
ipython = "^8.6.0"
invoke = "^1.7.3"

[tool.poetry.scripts]
emdy = "emdy.emdy:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
